### ISSUE TITLE
Images within a folder do not work

### ISSUE THREAD

**Issue by dsiddharth2** [dsiddharth2/php-zxing#13]
`D:\xampp\htdocs\php-zxing\src>"C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe" -cp D:\xampp\htdocs\php-zxing\src\bin\javase-3.3.3.jar;D:\xampp\htdocs\php-zxing\src\bin\core-3.3.3.jar;D:\xampp\htdocs\php-zxing\src\bin\jcommander-1.72.jar com.google.zxing.client.j2se.CommandLineRunner --recursive D:\xampp\htdocs\php-zxing\src\images`

Code like above gives,

`Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
        at sun.nio.fs.WindowsUriSupport.fromUri(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
        at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)`

**Comment by cattong** [comment]
same here, How can I fix it? it do not work on window ?

**Comment by cattong** [comment]
yes I fixed!  It take param of image file that use java URI class; java URI class is used for http|ftp|file. so the command can used for  decode file on net;
php code:
$zxingDecoder  = new \PHPZxing\PHPZxingDecoder();
 $zxingDecoder->setJavaPath('C:/"Program Files/Java"/jdk1.8.0_91/bin/java.exe');
 $fileUri = 'file:///' . str_replace('\\', '/', $filePath);
$data = $zxingDecoder->decode($fileUri);`
